#Script para ejecutar casos unitarios

from test_cases import CASE_EXTREME_OPTIMIZATION, CASE_MASSIVE_STOCK, CASE_STANDARD_WINDOWS, CASE_MULTI_GLASS_TYPES, CASE_HIGH_PRODUCTION, CASE_REF_NUMBER_PRESERVATION, CASE_NO_OVERLAP, CASE_MANY_SMALL_PIECES, CASE_FEWER_PLATES_PRIORITY, CASE_MULTIPLE_PIECES, CASE_SIMPLE_SCRAP, CASE_NEW_PLATE, CASE_ROTATION, CASE_WASTE_QUALITY, CASE_EMERGENCY_PLATE
from run_test_cases import validate_case

if __name__ == "__main__":
	validate_case(CASE_EXTREME_OPTIMIZATION, save_artifacts=True)
