# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "projects_form", to: "projects_form.js"
pin "projects_inline_edit", to: "projects_inline_edit.js"
pin "glasscutting_selects", to: "glasscutting_selects.js"
pin "glasscutting_table", to: "glasscutting_table.js"
pin "dvh_table", to: "dvh_table.js"
pin "preview_pdf", to: "preview_pdf.js"
pin "dvh_selects", to: "dvh_selects.js"
pin "glass_prices_calculator", to: "glass_prices_calculator.js"

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "projects_form", to: "projects_form.js"
pin "projects_inline_edit", to: "projects_inline_edit.js"
pin "glasscutting_selects", to: "glasscutting_selects.js"
pin "glasscutting_table", to: "glasscutting_table.js"
pin "dvh_table", to: "dvh_table.js"
pin "dvh_selects", to: "dvh_selects.js"
pin "glass_prices_calculator", to: "glass_prices_calculator.js"

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "projects_form", to: "projects_form.js"
pin "projects_inline_edit", to: "projects_inline_edit.js"
pin "glasscutting_selects", to: "glasscutting_selects.js"
pin "glasscutting_table", to: "glasscutting_table.js"
pin "dvh_table", to: "dvh_table.js"
pin "dvh_selects", to: "dvh_selects.js"
=========
pin "preview_pdf", to: "preview_pdf.js"
>>>>>>>>> Temporary merge branch 2
