# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "projects_form", to: "projects_form.js"
pin "projects_inline_edit", to: "projects_inline_edit.js"
pin "glasscutting_selects", to: "glasscutting_selects.js"
pin "glasscutting_table", to: "glasscutting_table.js"
pin "dvh_table", to: "dvh_table.js"
pin "dvh_selects", to: "dvh_selects.js"
pin "preview_pdf", to: "preview_pdf.js"
pin "glass_prices_calculator", to: "glass_prices_calculator.js"
pin "supply_editing", to: "supply_editing.js"
pin "@rails/request.js", to: "@rails--request.js.js" # @0.0.12
pin "glass_selects_common", to: "glass_selects_common.js"
pin "glassplate_selects", to: "glassplate_selects.js"
pin "scrap_selects", to: "scrap_selects.js"
pin "delete_confirmation", to: "delete_confirmation.js"
pin "quantity_editor", to: "quantity_editor.js"
pin "sweetalert2", to: "https://ga.jspm.io/npm:sweetalert2@11.22.3/dist/sweetalert2.all.js"
pin "utils", to: "utils.js"
